from serpent.machine_learning.context_classification.context_classifiers.cnn_inception_v3_context_classifier import CNNInceptionV3ContextClassifier
from serpent.machine_learning.context_classification.context_classifiers.cnn_xception_context_classifier import CNNXceptionContextClassifier

